name: Mastering test

on:
  workflow_call:
  push:

jobs:
  integration-test:
    runs-on: [self-hosted, linux, X64, xlarge, jammy]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup LXD
        run: lxd init --auto

      - name: Install Terraform
        run: sudo snap install terraform --classic

      - name: Deploy infra
        run: |
          git clone https://github.com/canonical/charmed-aether-sd-core.git
          cd charmed-aether-sd-core
          git checkout TELCO-1532-deploy-infra-with-tf
          cd terraform
          terraform init
          terraform apply -auto-approve



