name: CI workflow on push

on:
  push:

jobs:
  lint-report:
    uses: canonical/sdcore-github-workflows/.github/workflows/lint-report.yaml@main

  static-analysis:
    uses: canonical/sdcore-github-workflows/.github/workflows/static-analysis.yaml@main

  integration-test:
    uses: ./.github/workflows/integration-test.yaml
    secrets: inherit
